### ISSUE TITLE
Remove dependency on luafilesystem

### ISSUE THREAD

**Issue by Alloyed** [Alloyed/loverocks#11]
This is the only native binary needed to install loverocks, and windows users may/may not have a compiler installed
afaik it's only used to handle templates, which we can just as easily hardcode.

**Comment by Positive07** [comment]
luafilesystem is also required by luarocks if I'm not mistaken so it should be there most of the times

**Comment by Alloyed** [comment]
It's not, actually :o 

If 
https://www.archlinux.org/packages/community/any/luarocks/files/
is to be believed it actually only needs to run pure lua files, and then shell out to system commands to work. On windows it bundles those system commands as .exe files, probably from cygwin or something.

Good Idea (tm) related to #12 incoming: instead of making a bundle that includes love. We make it so loverocks can be hosted by your love install directly. Instead of installing through luarocks, you'd get a .love app and you'd do something like "love bundle.love loverocks deps; and love bundle.love love-release ." to actually use it

**Comment by Positive07** [comment]
Couldn't you use the luarocks functions instead? love-release does that.

Also I wouldn't dare to bundle luarocks as a .love file, it sounds tricky hahaha.
